name: Nathaniel
favicon: null
layout_spectrum: 0.13639216613955796
typography_spectrum: 0.5556326971855015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f0a0e'
    - '#050608'
    - '#ffffff'
    - '#2f2f2f'
    - '#8a8a8a'
  brandStrength: 0.75
  lightness: 0.1165000507608056
  saturation: 0.1317930375225842
  rhythmicContrast: 0.8158747951965779
purpose: []
