name: Nathaniel
favicon: null
layout_spectrum: 0.16216
typography_spectrum: 0.75082
title: 'Freedom & Power over Money, Relationships, & Lifestyle.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f0a0e'
    - '#050608'
    - '#ffffff'
    - '#2f2f2f'
    - '#8a8a8a'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
